### ISSUE TITLE
Can I run NicheCompass with zebrafish Visium data?

### ISSUE THREAD

**Issue by hkeremcil** [Lotfollahi-lab/nichecompass#64]
In the paper, I remember it saying that NicheCompass can be applied to spatial transcriptomics data at both single cell resolution and spot resolution. However, I think it was not tested with Visium data. Is it possible to use it with Visium data? I have both unannotated and unprocessed Visium data as well as Visium data after applying cell2location and deconvolution. Should I use the annotated and deconvolved data? Or is there another requirement for using spot resolution data? Because even after deconvolution, the structure looks significantly different. There aren't single cells in the adata.obs rows. There are only spots. And the spots have cell abundances in adata.obsm but it of course does not say which cell belongs to which cell type.

Lastly, the provided data only includes human_mouse_gene_orthologs.csv, mouse networks, and mouse metabolite enzymes & sensors. Do you have a suggestion about where to find the zebrafish versions?

Many thanks in advance!

**Comment by sebastianbirk** [comment]
Hi @hkeremcil,

Yes, it is also possible to use it with Visium data. We have tested it with Visium data as well, and, in the manuscript, we use a multimodal dataset that also has spot-level resolution. You just need to be aware that in the downstream analyses (e.g. when you create the cell-cell communication networks), you can't interpret it as networks of cells but rather networks of spots. 

For the mapping of orthologs, you can use Ensembl and follow this [documentation](https://www.ensembl.info/2009/01/21/how-to-get-all-the-orthologous-genes-between-two-species/).

**Comment by hkeremcil** [comment]
Hello @sebastianbirk,

Thank you very much for your response. This is insightful and it is good to know that it will work with Visium data. However, a very obvious problem emerges when we use spot-resolution data. The rows in adata.obs do not have cell types because they are not cells but instead spots. But the code requires a 'Main_molecular_cell_type' column in adata.obs, specifically in this part:

"""
cell_type_colors = create_new_color_dict(
    adata=adata,
    cat_key=cell_type_key)
"""

It gives an error if that column is missing. Spots cannot have cell types, as far as I know, since they contain multiple cells. How did you solve this issue when you used that multimodal dataset with spot-level resolution? Do I need to change the source code or are there different functions for data with spot-level resolution?

Since I applied the cell2location pipeline, I have cell type abundance values for each spot and cell type. I can use the most abundant cell types in each spot to fill the "Main_molecular_cell_type" column, but that eliminates most of the cell types, especially the immune cells we are interested in, and it only leaves a few abundant cell types. So, I am assuming there must be a different solution.

Thanks so much for your attention and support!

**Comment by sebastianbirk** [comment]
This code is not part of the model training workflow, so you could just skip it. To train NicheCompass, no labels are required. If you want to visualize the data (for which this code snippet is meant), then you would have to create some labels on spot level. This could be the majority cell type or also some more fine-grained label that you retrieve based on the spot's cell type abundance. Hope that helps.

**Comment by hkeremcil** [comment]
Thank you very much @sebastianbirk, I hadn't realized that it wasn't required for the training. That solves the problem! However, I do have another problem about using zebrafish data. I have the zebrafish versions of the gene orthologs file as well as metabolite_enzymes and metabolite_sensors files. But it still does not let me use any species other than human and mouse.

```
# Retrieve MEBOCOST GPs (source: enzyme genes; target: sensor genes)
mebocost_gp_dict = extract_gp_dict_from_mebocost_es_interactions(
    dir_path=mebocost_enzyme_sensor_interactions_folder_path,
    species=species,
    plot_gp_gene_count_distributions=True)
```
This code gives:
`ValueError: Species should be either human or mouse.`

Changing the source code to make the function accept other species results in errors in the following code snippets. Since I have the zebrafish versions of everything, I thought it could work if I just kept the species as 'mouse' and renamed everything accordingly while keeping the genes in those files as zebrafish genes. 

But that still gives me nichenet_lr_network_v2_mouse.csv and nichenet_ligand_target_matrix_v2_mouse.csv files that contain mouse genes, not zebrafish. Assuming I cannot readily find and download the zebrafish versions of these files, can I generate them myself? Would that work or would I still encounter errors due to using incompatible data in the later steps?

Thank you very much in advance! I genuinely appreciate the support and guidance. NicheCompass is a wonderful pipeline and I really hope I can make it work.
