### ISSUE TITLE
Compatibility with Visium HD data (8 micron)

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [Lotfollahi-lab/nichecompass#69]
Hello!
Just wanted to quickly ask if this tool is compatible with Visium HD data (8 microns, over 500k bins/spots) and if not, do you plan on expanding NicheCompass to be compatible with such data resolution?

Thanks!

**Comment by sebastianbirk** [comment]
Hi @Rafael-Silva-Oliveira,
Yes our tool is compatible with Visium HD data. Hope that helps :)

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi @Rafael-Silva-Oliveira, Yes our tool is compatible with Visium HD data. Hope that helps :)

Super! Is it possible to share the GP and the other csv files used in the single sample tutorial? Would be quite neat if this data could be fetched directly from the API as well, while also letting the user define their own GPs. 

Thanks

**Comment by sebastianbirk** [comment]
The GP data can be fetched directly via the "extract_gp_dict" functions by setting the "load_from_disk" parameter to False as described in the tutorial ;) Or are you facing any issue with that?
