### ISSUE TITLE
Gene program files

### ISSUE THREAD

**Issue by nimarafati** [Lotfollahi-lab/nichecompass#75]
Hi,

I would like to use this tool for my project which is human data. I tried to find gene programs but I am not sure whether all the files are in the repo. For example 
`
"../data/gene_programs/omnipath_lr_network.csv"
`.  which is loaded in `src/nichecompass/utils/gene_programs.py` file is not located under the `data`  directory. 

In other words, are all the required gene programs:
OmniPath (Ligand-Receptor GPs)
MEBOCOST (Enzyme-Sensor GPs)
NicheNet (Combined Interaction GPs)
In the repo under `data` folder?

**Comment by sebastianbirk** [comment]
Hello,
Thanks for your interest in our tool. If you follow the tutorial [here](https://nichecompass.readthedocs.io/en/latest/tutorials/notebooks/mouse_cns_single_sample.html), the gene program files will be downloaded. This is done via the `save_to_disk` parameter.

**Comment by nimarafati** [comment]
Thanks Sebastian. I was directly looking into the codes in the cloned repo and missed the link.
